### ISSUE TITLE
Cannot link pot to subproject due to project settings?

### ISSUE THREAD

**Issue by kalynx** [nijel/weblate#914]
Hi, I am still new to weblate and I really think you did an awesome job on it.

I would just like to ask a question.
I tried installing it using the bitnami stack version 2.3 for osx.
I am having a bit of trouble of setting up the subproject.
 
It is fine if I don't indicate a base pot file and uses the po file as a base file.
However, if I add in the pot file as base and set the format as Gettext POT, I get an error like below:
"Chosen file format does not support adding new translations as chosen in project settings."

In project settings, I checked Push on commit, Set Translation-Team header, and Enable Hooks.

I am stuck because I really couldn't use the po as base. I know it sounds like a very basic problem but I hope you can help.

Regards,
Joanne

**Comment by nijel** [comment]
It's in component settings (fixed in c3487958cb9486a14fb5bcd4b63243d735375321).

**Comment by kalynx** [comment]
Hi nijel, 

Thank you for the quick reply.
I applied the new error message but still could not make the component settings work. Is there something wrong with my component settings?

Adding in screenshots for reference.
![screen shot 2015-11-02 at 15 44 58](https://cloud.githubusercontent.com/assets/3908615/10875720/f37220fc-8178-11e5-9382-bd7c074086fb.png)
![screen shot 2015-11-02 at 15 45 28](https://cloud.githubusercontent.com/assets/3908615/10875719/f3715726-8178-11e5-9e05-6bd3e2bd10e0.png)
![screen shot 2015-11-02 at 15 45 48](https://cloud.githubusercontent.com/assets/3908615/10875721/f372e938-8178-11e5-8afd-e00479d940f0.png)
![screen shot 2015-11-02 at 15 46 12](https://cloud.githubusercontent.com/assets/3908615/10875722/f37745a0-8178-11e5-858d-2a9249fd7b9b.png)

Regards,
Joanne

**Comment by nijel** [comment]
Sorry, I misunderstood your original question... Now it seems like msginit is missing on the system (this is required for now, but this dependency will go away, see #883).

**Comment by kalynx** [comment]
Thank you for the reply. I used xgettext and msginit to create the pot and po files and I am still getting the same error message. Would it better for me to just update the Weblate version from 2.3.1 to the latest version?

**Comment by nijel** [comment]
It should work just fine, have you restarted the server since installing those?

**Comment by kalynx** [comment]
Hi, I just created a new instance in Linux and it works just fine. Thank you for the quick and fast support!
